### PR TITLE
Update to work with changes to UFO filters

### PR DESCRIPTION
**Pull request by ctgh**
## Description

Updates to account for moving the filter factory from oops to ufo.

## Issue(s) addressed

N/A

## Dependencies

build-group=https://github.com/JCSDA-internal/oops/pull/2760
build-group=https://github.com/JCSDA-internal/ufo/pull/3475
build-group=https://github.com/MetOffice/opsinputs/pull/225
build-group=https://github.com/MetOffice/nemo-feedback/pull/72

## Impact

N/A

## Checklist

- [ ] I have updated the unit tests to cover the change
- [ ] New functions are documented briefly via Doxygen comments in the code
- [ ] I have linted my code using cpplint
- [ ] I have run the unit tests
- [ ] I have run mo-bundle to check integration with the rest of JEDI and run the unit tests under all environments

### CODE REVIEW

**Review by mikecooke77 — APPROVED** [review]
All good to me.  Could you add the build group to the ufo and oops prs.  So that our CI passes.

**Comment by ctgh** [comment]
@mikecooke77 Thanks, now done.

**Review by twsearle — APPROVED** [review]
Thanks very much for adding this!

**Review by mikecooke77 — CHANGES_REQUESTED** [review]
The ci is failing because you need the same change in:
src/mains/orcamodel3DVar.cc
I'll push a fix.

**Review by mikecooke77 — APPROVED** [review]
Just pushed fix.  Hope thats OK.

**Comment by ctgh** [comment]
@mikecooke77 Thanks for spotting and fixing that.

**Pull request merged**
